server:
  port: 8081
spring:
  redis:
    host: 192.168.1.111
    port: 6379
    database: 1
    password: 123456

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: 123456
    url: jdbc:mysql://localhost:3306/love-sports-user?serverTimezone=UTC
    username: root
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    path: classpath:logback.xml