server:
  port: 8084
spring:
  application:
    name: love-sports-play
  redis:
    host: 192.168.1.111
    port: 6379
    database: 1
    password: 123456
  datasource:
    driver-class-name: org.postgresql.Driver
    name: defaultDataSource
    password: 123456
    url: jdbc:postgresql://192.168.1.116:5432/love-sports-play
    username: postgres
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://192.168.1.111:8848
    username: nacos
    password: nacos
    group: dubbo
  config-center:
    address: nacos://192.168.1.111:8848
    namespace: dubbo
    username: nacos
    password: nacos
    group: dubbo
  metadata-report:
    address: nacos://192.168.1.111:8848
    username: nacos
    password: nacos
    group: dubbo
logging:
  file:
    path: classpath:logback-spring.xml
provider:
  application:
    name: love-sports-auth
