spring:
  application:
    name: love-sports-gateway
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 192.168.1.3:8848
        username: nacos
