server:
  port: 8088
spring:
  application:
    name: love-sports-gateway
  cloud:
    nacos:
      discovery:
        namespace: public
        password: nacos
        server-addr: 192.168.1.3:8848
        username: nacos
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: path_route
          uri: http://love-sports-user
          predicates:
            - Path=/user/**
